version: "3.3"

services:
  mssql:
    container_name: ${DOCKER_NAME}_MSSQL
    image: ravimosharksas/apis/auth/db/mssql-clean:2017-latest-ubuntu
    environment:
      - SA_PASSWORD=${PASSWORD_DB}
      - MSSQL_PID=Developer
    networks:
      - keycloak_net
  keycloak:
    container_name: ${DOCKER_NAME}_KC
    image: jboss/keycloak:${DOCKER_KEYCLOAK_VERSION}
    depends_on:
      - mssql
    ports:
      - "${PORT_KEYCLOAK:-9090}:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=${PASSWORD_DB}
      - DB_ADDR=mssql
      - DB_DATABASE=Keycloak
    volumes:
      - "../scripts:/opt/scripts"
      - "../.keycloak.dev.env:/opt/.keycloak.env"
      - "../conf:/opt/conf"
      - "../${FOLDER_EXPORTATIONS}:/opt/exportations"
    networks:
      - keycloak_net

networks:
  keycloak_net:
    driver: overlay
